version: "3.7"
services:
  web:
    container_name: node-app
    hostname: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /usr/app/node_modules
      - ./src:/usr/app
    networks:
      - backend
    command: npm run dev
networks:
  backend:
    external:
      name: backend