version: "3.7"
services:
  app-dev:
    container_name: node-dev-app
    hostname: node-dev-app
    image: node-dev-app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - /usr/app/node_modules
      - ./app/src:/usr/app/src
    networks:
      - backend
    command: /bin/sh
networks:
  backend:
    external:
      name: backend